name: Build FRP for darwin_arm64

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'FRP version to build'
        required: true
        default: '0.24.1'

permissions:
  contents: read

jobs:
  build_darwin_arm64:
    name: Build darwin_arm64 binaries
    runs-on: macos-13
    env:
      GO_VERSION: '1.16'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Install build tools
        run: brew install make gcc git
          
      - name: Prepare dependencies
        run: |
          # 手动获取依赖
          mkdir -p $GOPATH/src/github.com/fatedier
          cd $GOPATH/src/github.com/fatedier
          git clone https://github.com/fatedier/kcp-go.git
          cd kcp-go
          git checkout cd167d2f15f4
          
          git clone https://github.com/fatedier/golib.git
          cd golib
          git checkout ff8cd814b049
          
      - name: Build for darwin_arm64
        run: |
          cd frp-${{ inputs.version || '0.24.1' }}
          export GO111MODULE=off  # 禁用 Go modules
          export GOPATH=$HOME/go
          export GOOS=darwin
          export GOARCH=arm64
          make
          
      - name: Package binaries
        run: |
          VERSION=${{ inputs.version || '0.24.1' }}
          cd frp-${VERSION}/bin
          mkdir -p frp_${VERSION}_darwin_arm64
          cp * frp_${VERSION}_darwin_arm64/
          tar -czvf frp_${VERSION}_darwin_arm64.tar.gz frp_${VERSION}_darwin_arm64
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frp_${{ inputs.version || '0.24.1' }}_darwin_arm64
          path: frp-${{ inputs.version || '0.24.1' }}/bin/frp_${{ inputs.version || '0.24.1' }}_darwin_arm64.tar.gz