name: Build FRP for darwin_arm64

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'FRP version to build'
        required: true
        default: '0.24.1'

permissions:
  contents: read

jobs:
  build_darwin_arm64:
    name: Build darwin_arm64 binaries
    runs-on: macos-13
    env:
      GO_VERSION: '1.16'
      FRP_VERSION: ${{ inputs.version || '0.24.1' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Install essential build tools
        run: |
          brew update
          brew install make gcc wget tar pkg-config

      - name: Debug environment
        run: |
          echo "系统信息:"
          uname -a
          echo "Go版本:"
          go version
          echo "环境变量:"
          env | sort
          
      - name: Download and extract FRP source
        run: |
          wget https://github.com/fatedier/frp/archive/refs/tags/v${FRP_VERSION}.tar.gz -O frp-source.tar.gz
          tar -xzf frp-source.tar.gz
          mv frp-${FRP_VERSION} frp-src
          ls -la frp-src
          
      - name: Prepare dependencies
        run: |
          cd frp-src
          # 处理现有go.mod文件
          if [ -f go.mod ]; then
            echo "使用现有go.mod文件"
            go mod edit -replace github.com/fatedier/kcp-go=github.com/fatedier/kcp-go@v2.0.0-20171023144637-cd167d2f15f4
            go mod edit -replace github.com/fatedier/golib=github.com/fatedier/golib@v0.1.0
          else
            echo "初始化新的go.mod文件"
            go mod init github.com/fatedier/frp
            go mod edit -replace github.com/fatedier/kcp-go=github.com/fatedier/kcp-go@v2.0.0-20171023144637-cd167d2f15f4
            go mod edit -replace github.com/fatedier/golib=github.com/fatedier/golib@v0.1.0
          fi
          
          go mod tidy
          echo "验证依赖关系:"
          go list -m all | grep fatedier || echo "无fatedier依赖"
          
      - name: Build for darwin_arm64
        run: |
          cd frp-src
          export GOOS=darwin
          export GOARCH=arm64
          export CGO_ENABLED=1
          make
          
      - name: Package binaries
        run: |
          mkdir -p release
          cd frp-src/bin
          mkdir -p frp_${FRP_VERSION}_darwin_arm64
          cp * frp_${FRP_VERSION}_darwin_arm64/
          tar -czvf ../../release/frp_${FRP_VERSION}_darwin_arm64.tar.gz frp_${FRP_VERSION}_darwin_arm64
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frp_${{ env.FRP_VERSION }}_darwin_arm64
          path: release/frp_${{ env.FRP_VERSION }}_darwin_arm64.tar.gz